version: '3.7'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "3020:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - symfonynet

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-container
    volumes:
      - ./:/var/www/html
    environment:
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - symfonynet

  db:
    image: mysql:9.0.1
    container_name: db-container
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
    networks:
      - symfonynet

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma-container
    restart: always
    ports:
      - 3021:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USERNAME}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 300
    networks:
      - symfonynet

networks:
  symfonynet:
    driver: bridge